name: Build C++ functions

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc

    - name: Compile to .dll
      shell: msys2 {0}
      run: |
        g++ -Ofast -Wall -shared -std=c++20 -static -o main.dll main.cpp object.cpp -lgdi32
        ls -l main.dll

    - name: Commit and push .dll file
      run: |
        git config --global user.name "Ethan Chan"
        git config --global user.email "esamuelchan@gmail.com"
        git add . -f
        git commit -m "Auto-build DLL files using g++" || echo "No changes to commit"
        git push https://$GH_PAT@github.com/eschan145/collisions.git main
      env:
        # A GitHub PAT must be set up as an Actions secret in the repository
        GH_PAT: ${{ secrets.GH_PAT }}
